language: elixir
elixir:
  - 1.5.2
  - 1.4.5
  - 1.3.4
  - 1.2.6
otp_release:
  - 20.1
  - 19.3
  - 18.3
branches:
  only:
  - master
before_install:
  - mix local.rebar --force
script:
  - SIPHASH_IMPL=native mix test --trace
  - SIPHASH_IMPL=embedded mix test --trace
after_success:
  - SIPHASH_IMPL=embedded mix coveralls.travis
