language: elixir
elixir:
  - 1.1.1
otp_release:
  - 18.0
script:
  - HASH_IMPL=native mix test --trace
  - HASH_IMPL=embedded mix test --trace
after_success:
  - HASH_IMPL=embedded MIX_ENV=test mix coveralls.travis
