language: elixir
elixir:
  - 1.2.1
otp_release:
  - 18.2
script:
  - SIPHASH_IMPL=native mix test --trace
  - SIPHASH_IMPL=embedded mix test --trace
after_success:
  - SIPHASH_IMPL=embedded MIX_ENV=test mix coveralls.travis
