language: elixir
elixir:
  - 1.1.1
otp_release:
  - 18.0
script:
  - STATE_IMPL=native UTIL_IMPL=native mix test --trace
  - STATE_IMPL=embedded UTIL_IMPL=embedded mix test --trace
after_success:
  - STATE_IMPL=embedded UTIL_IMPL=embedded MIX_ENV=test mix coveralls.travis
