language: elixir
elixir:
  - 1.4.0
  - 1.3.4
  - 1.2.6
otp_release:
  - 19.2
  - 18.3
before_install:
  - mix local.rebar --force
script:
  - SIPHASH_IMPL=native mix test --trace
  - SIPHASH_IMPL=embedded mix test --trace
after_success:
  - SIPHASH_IMPL=embedded mix coveralls.travis
branches:
  only:
    - master
